### ISSUE TITLE
Switch to @abandonware/noble for modern Node compatibility?

### ISSUE THREAD

**Issue by akx** [akx/ruuvidriver#1]
* Vendor in https://github.com/Espesen/node-ruuvitag
* Switch from `noble` to `@abandonware/noble`
* ???
* Profit?

**Comment by Glenf** [comment]
Changes to dependencies seem to fix things. This works for me, so I'm fine for now :)

https://github.com/Glenf/ruuvidriver/tree/fix/node-ruuvitag-noble

**Comment by okko** [comment]
This was done in 978a15eedeb5570425531fa5307945c623841122, is in master
