### ISSUE TITLE
FIX: Issue on packages.json

### ISSUE THREAD

**Issue by mmaraa** [akx/ruuvidriver#2]
There is an issue in packages.json file:

{
  "name": "ruuvidriver",
  "version": "0.1.0",
  "main": "index.js",
  "license": "MIT",
  "scripts": {
    "start": "node index.js",
  },

Script should be without a following comma.

    "start": "node index.js", -->     "start": "node index.js"

**Comment by akx** [comment]
Thanks for the heads-up! Wonder how I haven't noticed that before.
